{
  "sksl": {
    "entrypoint": "starfield_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float cumulativeX;\nuniform float cumulativeY;\nuniform float time;\n\nvec4 f;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 u = FLT_flutter_local_FlutterFragCoord() / uSize;\n    f -= f;\n    for (float i = 0.100000001490116119384765625; i < 0.89999997615814208984375; i += 0.039999999105930328369140625)\n    {\n        vec3 p = vec3(u + (vec2(cumulativeX, cumulativeY) / vec2(i)), i);\n        p = abs(vec3(1.0) - mod(p, vec3(2.0)));\n        float a = length(p);\n        float c = 0.0;\n        for (float i_1 = 0.100000001490116119384765625; i_1 < 0.89999997615814208984375; i_1 += 0.039999999105930328369140625)\n        {\n            p = ((abs(p) / vec3(a)) / vec3(a)) - vec3(0.699999988079071044921875);\n            float b = length(p);\n            c += abs(a - b);\n            a = b;\n        }\n        c *= c;\n        vec3 starColor = vec3(1.0);\n        starColor.x += ((i * 1.5) + (sin(cumulativeX * 0.20000000298023223876953125) * 0.5));\n        starColor.z += (((1.0 - i) * 0.699999988079071044921875) + (cos(cumulativeY * 0.5) * 0.5));\n        f += ((vec4(starColor, 0.0) * c) / vec4(70000.0));\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return f;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "cumulativeX",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "cumulativeY",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "time",
        "rows": 1,
        "type": 10
      }
    ]
  }
}